apiVersion: v1
kind: Service
metadata:
  name: my-portfolio-app-service
spec:
  type: ClusterIP
  selector:
    app: altaf-shaikh-portfolio-nextjs-pod
    type: next-js-frontend-app-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000